spring:
  application:
    name: ecom-registration-server
  profiles:
    active:
    - dev
    
server:
  port: 8085
  
#--------------------------------------
# Logging Properties
#--------------------------------------
logging:
  level:
    ROOT: DEBUG
    '[dev.atanu.ecom]': DEBUG
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 20MB     
  file:
    name: log/ecom-registration-server.log
  
  
#--------------------------------------
# Eureka Server Properties
#--------------------------------------
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://127.0.0.1:8085/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
